# Generated by Django 5.0.1 on 2024-02-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDOclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('task_Assign_by', models.CharField(max_length=100)),
                ('task_complete_to', models.CharField(max_length=100)),
                ('Complete_By', models.DateField()),
            ],
        ),
    ]
